feat: make bootstrap script POSIX compliant

diff --git a/.config/yadm/bootstrap b/.config/yadm/bootstrap
--- a/.config/yadm/bootstrap
+++ b/.config/yadm/bootstrap
@@ -1,6 +1,6 @@
-#!/bin/env bash
+#!/bin/env sh
 
-set -euo pipefail # exit on error and unset variables
+set -eu # exit on error and unset variables
 
 # Function to install Homebrew on macOS
 install_brew() {
@@ -17,47 +17,33 @@ install_brew() {
 
 # Function to install shell utilities on Arch Linux and macOS
 install_shell_utils() {
-	if [ -f /etc/arch-release ]; then
-		printf "\n--- Updating and upgrading system ---\n\n"
-		sudo pacman -Syu
-
-		printf "\n--- Setting up shell utils for Arch Linux ---\n\n"
-		sudo pacman -S --needed --noconfirm \
-			zsh \
-			zsh-autosuggestions \
-			zsh-syntax-highlighting \
-			zsh-completions \
-			git \
-			curl \
-			bat \
-			eza \
-			fd \
-			fzf \
-			ripgrep \
-			tmux \
-			tree \
-			base-devel \
-			zoxide \
-			gum \
-			xclip \
-			neovim \
-			starship \
-			trash-cli \
-			ttf-jetbrains-mono-nerd \
-			ttf-nerd-fonts-symbols \
-			fastfetch
-
-		if ! command -v yay >/dev/null 2>&1; then
-			printf "\n--- Installing yay AUR helper ---\n\n"
-			tmp_dir=$(mktemp -d)
-			git clone https://aur.archlinux.org/yay.git "$tmp_dir/yay"
-			(cd "$tmp_dir/yay" && makepkg -si)
-			rm -rf "$tmp_dir"
-
-			yay -S --needed --noconfirm \
-				sesh-bin
+	if [ "$system_type" = "Linux" ]; then
+		. /etc/os-release
+		if [ "$ID" = "arch" ]; then
+			if [ ! -x "$(command -v ansible)" ]; then
+				printf "\n--- Setting Ansible ---\n\n"
+				sudo pacman -Syu --noconfirm ansible python python-pip python-argcomplete
+				return
+			fi
+		elif [ "$ID" = "ubuntu" ]; then
+			if ! dpkg -s ansible >/dev/null 2>&1; then
+				printf "\n--- Setting Ansible ---\n\n"
+				sudo apt-get update
+				sudo apt-get install -y software-properties-common
+				sudo apt-add-repository -y ppa:ansible/ansible
+				sudo apt-get update
+				sudo apt-get install -y ansible
+				sudo apt-get install -y python3 python3-pip python3-watchdog python3-argcomplete
+				sudo activate-global-python-argcomplete
+			fi
+		else
+			echo "Unsupported OS"
+			exit 1
 		fi
-	elif [ "$system_type" == "Darwin" ]; then
+		printf "\n--- Starting Ansible Playbook ---\n\n"
+		export ANSIBLE_CONFIG="$HOME"/.config/yadm/ansible/ansible.cfg
+		ansible-playbook -K -i "localhost," -c local "$HOME"/.config/yadm/ansible/setup.yml
+	elif [ "$system_type" = "Darwin" ]; then
 		printf "\n--- Setting up shell utils for macOS ---\n\n"
 		brew install \
 			bat \
@@ -75,28 +61,13 @@ install_shell_utils() {
 	fi
 }
 
-# Function to setup Neovim configuration
-setup_nvim() {
-	printf "\n--- Setting up neovim ---\n\n"
-	if [ -d ~/.config/nvim ]; then
-		echo "neovim config already exists, do you want to overwrite it? [y/N]"
-		read -r response
-		if [ "$response" == "y" ] && [ "$response" == "Y" ]; then
-			mv ~/.config/nvim ~/.config/nvim.bak
-			git clone https://github.com/razobeckett/nvim.git ~/.config/nvim
-			nvim --headless +Lazy +qall
-		fi
-	fi
-}
-
 # Main script execution
 system_type=$(uname -s)
 
-if [ "$system_type" == "Darwin" ]; then
+if [ "$system_type" = "Darwin" ]; then
 	install_brew
 fi
 
 install_shell_utils
-setup_nvim
 
 printf "\n*** Script completed successfully. {^_^} ***\n"
